name = "float-model"
version = "0.1.0"
defaultTargets = ["FloatModel", "FloatModelTests"]

[[lean_lib]]
name = "FloatModel"

[[lean_lib]]
name = "FloatModelTests"

[[lean_exe]]
name = "testfloat-check"
root = "FloatModelTests.TestFloatCheck"
