#!/usr/bin/env bash
# Checks the model against multiplication, division, and square root test
# vectors generated by the UCBTEST-derived programs in scripts/ucbtest-gen/
# (adaptations of ucbmultest, ucbdivtest, and ucbsqrtest that emit their
# number-theoretically hard cases in Berkeley TestFloat format).
#
# Usage: scripts/run-ucbtest-gen.sh
#
# The vector files are written to vendor/ucbtest-vectors/f64_{mul,div,sqrt}.txt
# and can be re-checked by hand with e.g.
#   lake exe testfloat-check f64_mul < vendor/ucbtest-vectors/f64_mul.txt
# Set NTESTS=<n> to change the generators' test-case count (default 10000;
# the vector counts differ per operation since each generated configuration
# yields a different number of vectors).

set -uo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gen="$root/scripts/ucbtest-gen"
out="$root/vendor/ucbtest-vectors"
check="$root/.lake/build/bin/testfloat-check"
cc="${CC:-cc}"

mkdir -p "$out"

# -frounding-math: the mul generator switches the rounding direction at run
# time; -ffp-contract=off: the generators' exactness arguments assume one
# rounding per operation, so no fused multiply-adds.
for op in mul div sqrt; do
  "$cc" -O2 -std=c99 -frounding-math -ffp-contract=off \
    -o "$out/ucbgen-$op" "$gen/$op.c" -lm || exit 2
done

(cd "$root" && lake build testfloat-check) || exit 2

status=0
for op in mul div sqrt; do
  vectors="$out/f64_$op.txt"
  "$out/ucbgen-$op" ${NTESTS:+"$NTESTS"} > "$vectors" || { status=2; continue; }
  echo "f64_$op:"
  "$check" "f64_$op" < "$vectors" || status=1
done
exit "$status"
