/*
 * Shared support for the vector generators adapted from the UCBTEST suite
 * (mul.c, div.c, sqrt.c in this directory). The generators emit binary64
 * test vectors in Berkeley TestFloat format on stdout:
 *
 *   <operand1> [<operand2>] <expected> <flags>
 *
 * with each float printed as its 16-digit hexadecimal bit pattern, suitable
 * for `lake exe testfloat-check <operation>`.
 */
#ifndef UCBGEN_H
#define UCBGEN_H

#include <fenv.h>
#include <inttypes.h>
#include <math.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef uint32_t UINT32;
typedef int32_t INT32;

/* The original programs are generic over the tested precision; this
 * adaptation is fixed to binary64 ("DP" in UCBTEST terms). */
#define GENERIC double
#define ZERO 0.0
#define ONE 1.0
#define TWO 2.0
#define FOUR 4.0
#define significand_length 53

/* Number of test cases to generate; settable as the program's first
 * command-line argument, like in the original programs. */
static UINT32 ntests = 10000;

static uint64_t bits_of(GENERIC x)
{
	uint64_t u;
	memcpy(&u, &x, sizeof u);
	return u;
}

/* Every case generated by these programs is inexact and raises no other
 * exception, so the TestFloat exception-flags field is always 01. (The
 * checker ignores the flags; they are emitted only to match the format.) */
static void emit2(GENERIC a, GENERIC b, GENERIC expected)
{
	printf("%016" PRIX64 " %016" PRIX64 " %016" PRIX64 " 01\n",
	       bits_of(a), bits_of(b), bits_of(expected));
}

static void emit1(GENERIC a, GENERIC expected)
{
	printf("%016" PRIX64 " %016" PRIX64 " 01\n",
	       bits_of(a), bits_of(expected));
}

/* The expected results are derived by number-theoretic means, independently
 * of the operation under test, but as a safeguard against adaptation bugs
 * every vector is cross-checked against the host arithmetic (correctly
 * rounded on any IEEE 754 machine) before it is emitted. */
static void die(const char *fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fputc('\n', stderr);
	exit(2);
}

/* IEEE rounding direction control (ieee_flags in the original). The
 * generators must be compiled with -frounding-math so that the compiler
 * does not move floating-point operations across these calls. */
static void round_nearest(void) { fesetround(FE_TONEAREST); }
static void round_positive(void) { fesetround(FE_UPWARD); }
static void round_zero(void) { fesetround(FE_TOWARDZERO); }

/*
 * Random number algorithm is based on the additive number generator
 * described in Knuth's The Art of Computing, Vol II (second edition)
 * section 3.2.2. It returns a positive random integer.
 *
 * Verbatim from UCBTEST's mul.c/div.c, which each carry a copy. The
 * original seeding routine with the fixed seed 0 (the default in both
 * programs) makes Y[] start exactly from this table, so seeding is dropped
 * and the generated vector files are reproducible.
 */
static UINT32 rng_Y[55] = {
 0x8ca0df45, 0x37334f23, 0x4a5901d2, 0xaeede075, 0xd84bd3cf,
 0xa1ce3350, 0x35074a8f, 0xfd4e6da0, 0xe2c22e6f, 0x045de97e,
 0x0e6d45b9, 0x201624a2, 0x01e10dca, 0x2810aef2, 0xea0be721,
 0x3a3781e4, 0xa3602009, 0xd2ffcf69, 0xff7102e9, 0x36fab972,
 0x5c3650ff, 0x8cd44c9c, 0x25a4a676, 0xbd6385ce, 0xcd55c306,
 0xec8a31f5, 0xa87b24ce, 0x1e025786, 0x53d713c9, 0xb29d308f,
 0x0dc6cf3f, 0xf11139c9, 0x3afb3780, 0x0ed6b24c, 0xef04c8fe,
 0xab53d825, 0x3ca69893, 0x35460fb1, 0x058ead73, 0x0b567c59,
 0xfdddca3f, 0x6317e77d, 0xaa5febe5, 0x655f73e2, 0xd42455bb,
 0xe845a8bb, 0x351e4a67, 0xa36a9dfb, 0x3e0ac91d, 0xbaa0de01,
 0xec60dc66, 0xdb29309e, 0xcfa52971, 0x1f3eddaf, 0xe14aae61,
};
static int rng_j = 23, rng_k = 54;

static UINT32 Rand(void)
{
	UINT32 m;
	m = rng_Y[rng_j] + rng_Y[rng_k];
	rng_Y[rng_k] = m;
	rng_j = rng_j - 1;
	rng_k = rng_k - 1;
	if (rng_j < 0) rng_j = 54;
	if (rng_k < 0) rng_k = 54;
	return m & 0x7fffffff;
}

#endif /* UCBGEN_H */
